import React from 'react';
import { Helmet } from 'react-helmet-async';

const Terms = () => {
  return (
    <>
      <Helmet>
        <title>Terms of Service - REI Calculator Pro</title>
        <meta name="description" content="Terms of Service for REI Calculator Pro - Important disclaimers and terms for using our real estate investment calculators." />
      </Helmet>

      <div className="min-h-screen bg-gray-50">
        {/* Hero Section */}
        <section className="hero-gradient text-white py-20">
          <div className="container mx-auto px-4">
            <div className="max-w-4xl mx-auto text-center">
              <h1 className="text-4xl md:text-6xl font-bold mb-6 leading-tight">
                Terms of Service
              </h1>
              <p className="text-xl md:text-2xl text-blue-100">
                Important information about using our calculators
              </p>
            </div>
          </div>
        </section>

        {/* Content */}
        <section className="py-20">
          <div className="container mx-auto px-4">
            <div className="max-w-4xl mx-auto bg-white rounded-lg p-8 shadow-md">
              <p className="text-sm text-gray-500 mb-8">Last updated: December 2024</p>

              <div className="space-y-8">
                <div>
                  <h2 className="text-2xl font-bold text-gray-800 mb-4">Acceptance of Terms</h2>
                  <p className="text-gray-600 leading-relaxed">
                    By accessing and using REI Calculator Pro ("the Service"), you accept and agree to be bound by the terms 
                    and provision of this agreement. If you do not agree to these terms, please do not use our Service.
                  </p>
                </div>

                <div>
                  <h2 className="text-2xl font-bold text-gray-800 mb-4">Informational Purposes Only</h2>
                  <p className="text-gray-600 leading-relaxed mb-4">
                    <strong>Important Disclaimer:</strong> All calculators and tools provided on this website are for 
                    <strong> informational and educational purposes only</strong>. They are not intended to provide financial, 
                    investment, legal, or professional advice.
                  </p>
                  <p className="text-gray-600 leading-relaxed">
                    The calculations, results, and projections generated by our tools should not be considered as professional 
                    financial or investment advice. Real estate investments involve risk, and past performance does not guarantee future results.
                  </p>
                </div>

                <div>
                  <h2 className="text-2xl font-bold text-gray-800 mb-4">Professional Consultation Required</h2>
                  <p className="text-gray-600 leading-relaxed">
                    Before making any investment decisions, you should:
                  </p>
                  <ul className="list-disc list-inside text-gray-600 mt-2 space-y-1">
                    <li>Consult with qualified financial advisors, real estate professionals, and legal counsel</li>
                    <li>Conduct your own due diligence and research</li>
                    <li>Consider your personal financial situation and risk tolerance</li>
                    <li>Verify all calculations and assumptions independently</li>
                  </ul>
                </div>

                <div>
                  <h2 className="text-2xl font-bold text-gray-800 mb-4">No Warranty on Calculations</h2>
                  <p className="text-gray-600 leading-relaxed">
                    While we strive for accuracy, we make no warranty or guarantee regarding the accuracy, completeness, 
                    or reliability of any calculations, results, or information provided by our tools. Market conditions, 
                    local factors, and individual circumstances can significantly affect actual investment outcomes.
                  </p>
                </div>

                <div>
                  <h2 className="text-2xl font-bold text-gray-800 mb-4">User Responsibility</h2>
                  <p className="text-gray-600 leading-relaxed">
                    You are solely responsible for:
                  </p>
                  <ul className="list-disc list-inside text-gray-600 mt-2 space-y-1">
                    <li>Verifying the accuracy of all input data and assumptions</li>
                    <li>Understanding the limitations of calculator results</li>
                    <li>Making your own independent investment decisions</li>
                    <li>Ensuring compliance with all applicable laws and regulations</li>
                  </ul>
                </div>

                <div>
                  <h2 className="text-2xl font-bold text-gray-800 mb-4">Limitation of Liability</h2>
                  <p className="text-gray-600 leading-relaxed mb-4">
                    To the fullest extent permitted by law, REI Calculator Pro and its operators shall not be liable for any:
                  </p>
                  <ul className="list-disc list-inside text-gray-600 space-y-1">
                    <li>Investment losses or financial damages</li>
                    <li>Decisions made based on calculator results</li>
                    <li>Errors or omissions in calculations or information</li>
                    <li>Interruptions to service or technical issues</li>
                  </ul>
                </div>

                <div>
                  <h2 className="text-2xl font-bold text-gray-800 mb-4">Acceptable Use</h2>
                  <p className="text-gray-600 leading-relaxed">
                    You agree to use our Service only for lawful purposes and in a way that does not infringe upon the rights 
                    of others or restrict their use and enjoyment of the Service. You may not attempt to interfere with, 
                    compromise the security of, or decipher any transmissions to or from our servers.
                  </p>
                </div>

                <div>
                  <h2 className="text-2xl font-bold text-gray-800 mb-4">Intellectual Property</h2>
                  <p className="text-gray-600 leading-relaxed">
                    All content, including calculator logic, design, text, and graphics, is owned by REI Calculator Pro 
                    and protected by intellectual property laws. You may use our calculators for personal use but may not 
                    reproduce, distribute, or create derivative works without permission.
                  </p>
                </div>

                <div>
                  <h2 className="text-2xl font-bold text-gray-800 mb-4">Service Availability</h2>
                  <p className="text-gray-600 leading-relaxed">
                    We strive to maintain continuous service availability but do not guarantee uninterrupted access. 
                    We reserve the right to modify, suspend, or discontinue any part of our Service at any time without notice.
                  </p>
                </div>

                <div>
                  <h2 className="text-2xl font-bold text-gray-800 mb-4">Changes to Terms</h2>
                  <p className="text-gray-600 leading-relaxed">
                    We reserve the right to modify these terms at any time. Changes will be posted on this page with an updated date. 
                    Continued use of the Service after changes constitutes acceptance of the new terms.
                  </p>
                </div>

                <div>
                  <h2 className="text-2xl font-bold text-gray-800 mb-4">Contact Information</h2>
                  <p className="text-gray-600 leading-relaxed">
                    If you have questions about these Terms of Service, please contact us through our contact form.
                  </p>
                </div>

                <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6 mt-8">
                  <div className="flex items-start">
                    <i className="fas fa-exclamation-triangle text-yellow-600 mr-3 mt-1"></i>
                    <div>
                      <h3 className="font-bold text-yellow-800 mb-2">Important Reminder</h3>
                      <p className="text-yellow-700 text-sm">
                        Real estate investing involves significant financial risk. Our calculators provide estimates based on your inputs 
                        but cannot account for all variables that affect real estate investments. Always consult with qualified professionals 
                        before making investment decisions.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
};

export default Terms;